name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # Генерируем недостающие файлы android на лету
            - run: flutter create . --platforms android --org com.dikobu.prognoz

      # Вставляем разрешения на интернет и открытие ссылок прямо в сгенерированный файл
      - name: Patch Android Manifest for Internet and URLs
        run: |
          MANIFEST=android/app/src/main/AndroidManifest.xml
          # Добавляем разрешение на интернет
          sed -i '/<application/i \    <uses-permission android:name="android.permission.INTERNET" />' $MANIFEST
          # Добавляем блок <queries> для Android 11+ (чтобы работали ссылки)
          sed -i '/<application/i \    <queries><intent><action android:name="android.intent.action.VIEW" /><data android:scheme="https" /></intent></queries>' $MANIFEST

      - run: flutter build apk --release
